services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #   - ".:/app"
    #   - "/app/node_modules"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres-data:
